language: node_js
node_js: '10'
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: VsUw/UqWGTLVhqc2Xj66zLWxo+De35GnDqfzMGJXaFeySTIGF7a/iSUTGUExtveJAvf7Q/iAIOg2LJuavKpU3kl2LXGmqXbmHjRDtBTgFP1GQZFjVFfeikrVmwfVFFAD077guAUaI+PJ+ATwHGBU2fxWgKUy25DpKsud6cNe/CO+TyiUNBeGrI4/XVgD+9IA29fhAUaPXyckiUtlcfocX71MxABomtDLhW41LrC52kUj1iFIqwl3DZUTXrVeSxZf1LgLUrb2ZeAwdotaEp1mmdAfDWl+N457qemu79g3qQ7OeRbWgBRyOQALFDpX9U4Nk9z/cBQEPis2IQF1dpjIAkgDaEHDB9KqHVimbdLEYnvxnx56oniVoxQD0JW8QNHUCnkO44bmxdu/nT4sebiMNZjRnbcwyQfypqCGtT+ZowyB4pdLZ7cytnE5gNKM9ywGq2oLMYirvrOQJZXkCH1OgY/wplMuiVB7Hi6rUbDTy9akSEZ6QgySU2Glo4SDdXG2D3F4TqfgV9Wy+uYTr1OgIa9hB2XzXbliHDv277bfXFJ1tetcfs7qZQI32cRPdCwqyNSeHBg3j/9/nwOoQRix2vd7LrSKn2ZtFoyUPlrO8PoP1XyfGDLZKWf7kgzWUyn2/rSVHc8vIu3O7p9783AYcBRktQ6Yn8TjDwN7CRU9HgU=
