language: node_js
node_js: '10'
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: zrvqELaPpyGej7gBHJJYsa2QTU3TzfCveHCa6TnZkq2198i9DY4Cuc/GDyMupoBCROL7oAvNaxkin/z2UGJr158YeXqd4Qo/wsXzD+YH/GpobdbD41ypzZnEzzbNshTfBXbHi9FlIf0FyOWPrZjdYBPqycGumKKxaxaDS62DJDrcnQe1gf2HJ+em+U8KH4qDZdfa8+qTV0rKvoLsPOPz6V/Wn4X/xyEKCE5YoHzvPAHOBO10mldYdKHhcvQF+zPhO2Dl1uSZqb5Fmmt2ykUQEZDZnIHMuoO3qv4TYnhHOQpDTGE9W4kRo2DlaXDiA0838o7MFYeCGl9RvUTy7QVHXGaPwmw99HFHKCOxhZbJswBL7XvfbGdpPAmsgd/HnP3G6v5ZpckO3nThw1AFS+pYOJkOHRU77ASFxFYH4v5LHT8ddDWJYdklLSvfC9I3X1jE++JgIED1dFGZ+YvXkQY5QwvZtbXJLC9rOtpBJxU+gxaRhhoreR2CbjwVO49eE95jq9SSwFaUde8yt/M3THWvY66oBpaFHHU8MEHePlPvrfyvkgknX8D0Zx/U9OVYZ6xcYXW6wx34tyiQIAeasV3uEOPU57Bwrryz9/M1ig2gUMGutk9Sdilo/F2z0tkzzC5V4OsStujmpBCm3aH4iV5W0SBtYt+NFkq778iEYBksm0M=
