language: node_js
node_js: '10'
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: IQSacu/qT+S5+mMGbkYx3KcBxFcUWQdnbjAsohIo6x580UWWOeeXnls0YVEtVx/ai55GbYl88A6Xs67I2VWtTLwlgB2vr0/W2sTExOMyj3OToJGVY0usDSiTRtpLwxXP4osNkLuFIl94HpXtJA6e7b8HDmITaiBseEuS6TfoipcwqeWhFTUqrwexej0eeZyjMoY26vEKOhxpajxiStMEe6huj5IOxuex1qAC052qjpHOtaA0gSqqZrai6sKB2kQymcMRYSUF1RcbWWyQR9giM6wQ9UjwJxchuyjQWB3WlV5TDM8c8DOATzOygWDwNcy2t3H3OnmvuYFJzS/oBjz7qkG9TgbfXoyHPhj5XCKKtT3I0S5g1NgfRUCdvyvO+azFu2waXjr0bLpJnF/zKVPGKJ3jXCQxLwYd1P7nQ0bbxCGKwSDqys8R7Kyccavws37dwciwD4wxo6dCFj6ZOQ/Kndt3DEONy4bgveuhY38hPiY37z+/uEPBoTPDKNuYQHfWh5LcXQZF191z6oMdrkd++PA5D/U/bYIUC8NDROuNtQv6/Nw/Ek7/ntWoezjFKf+JLDpfv0M3KswlZ5zkd41z5q7sotCaMWe2tW7HnwUjeUE2abVJz0wGDFJWaOLBRqE6OrEkML3LsPwtO03ngR8/uWm/J71D1oSzE32zka3AUnw=
